### ISSUE TITLE
Add Missing Features for Course Recommendation System

### ISSUE THREAD

**Issue by TheImperialEmperor** [TheImperialEmperor/course-recommend-system#1]
There are a few key features missing from the course recommendation system that would greatly enhance its functionality. Error handling needs to be implemented for scenarios where no courses match a given keyword. Additionally, a feature for recommending courses based on description similarity using cosine similarity is needed. Lastly, a function to recommend popular courses based on reviews and ratings should be added. 
Contributions are welcome, and any improvements or suggestions to implement these features would be greatly appreciated!

**Comment by Soham-Niungare** [comment]
I have addressed the missing features by adding proper error handling for cases where no courses match a given keyword. I’ve also implemented a feature that recommends courses based on description similarity using cosine similarity. Additionally, a function to recommend popular courses based on reviews and ratings has been integrated. This should enhance the overall functionality of the course recommendation system

**Comment by TheImperialEmperor** [comment]
Thank you for addressing the missing features. The error handling for keyword-based searches, description-based recommendations using cosine similarity, and the popular courses feature based on reviews and ratings are valuable additions that improve both functionality and user experience.
I’ve reviewed the changes, and everything is well-implemented. I appreciate your thorough work on this
